## Upload sentry results when Server CI Master is completed
name: Sentry Upload

on:
  workflow_run:
    workflows:
      - "Server CI Master"
    types:
      - completed

jobs:
  sentry:
    name: Send build info to sentry
    runs-on: ubuntu-22.04
    env:
      SENTRY_AUTH_TOKEN: ${{ secrets.MM_SERVER_SENTRY_AUTH_TOKEN }}
      SENTRY_ORG: ${{ secrets.MM_SERVER_SENTRY_ORG }}
      SENTRY_PROJECT: ${{ secrets.MM_SERVER_SENTRY_PROJECT }}
    steps:
      - name: cd/Checkout mattermost project
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: cd/Create Sentry release
        uses: getsentry/action-release@50f4a1a3799e059c182a73c30bbebc89739af2db # v1.10.2

